variables:
    USER: "tuckkin"
    DEV_NAMESPACE: "user-tuckkin"
    DEV_INGRESS_HOST: "user-tuckkin-dev.tp.aws.bizilife.net"
    PROD_NAMESPACE: "user-tuckkin-prod"
    PROD_INGRESS_HOST: "user-tuckkin-prod.tp.aws.bizilife.net"
    HARBOR_REGISTRY: "harbor.tp.aws.bizilife.net"
    HARBOR_REGISTRY_USER: "tuckkin"
    HARBOR_REGISTRY_PASSWORD: "fslsna17okfh5u6ds73nebbi55penzqr"
    HARBOR_IMAGE: "harbor.tp.aws.bizilife.net/cn101/cn101-devops-app"
    PASSWORD: "No1knows!"

stages:
    - build
    - test
    - publish
    - staging
    - production

build-app:
    stage: build
    image: openjdk:13-alpine
    script:
        - ./mvnw install -DskipTests
    artifacts:
        paths:
            - ./target/*.jar

test-app:
    stage: test
    image: openjdk:13-alpine
    before_script:
        - apk --no-cache add curl
        - apk --no-cache add jq
    script:
        #- java -jar ./target/app-0.0.1-SNAPSHOT.jar &
        #- sleep 5
        #- JSON=$(curl http://localhost:8080/rest/app/info)
        #- echo $JSON
        #- echo $JSON | jq .port
        #- curl "http://localhost:8080/rest/app/info" | grep -q "port"
        - exit 0

push-image-to-staging-container-registry:
    stage: publish
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo "create container image and push the image to the staging container registry"
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        #- /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:$USER
    dependencies:
        - build-app
    only:
        - master

push-image-to-production-container-registry:
    stage: publish
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo $CI_REGISTRY_IMAGE
        - echo $CI_PROJECT_DIR
        - echo "create container image and push the image to the production container registry"
        - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$HARBOR_REGISTRY_USER\",\"password\":\"$HARBOR_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $HARBOR_IMAGE:$USER
    dependencies:
        - build-app
    only:
        - master

deploy-to-dev-k8s-cluster:
    stage: staging
    image: dtzar/helm-kubectl
    before_script:
        - apk --no-cache add curl bash
        - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        - mv kustomize /usr/local/bin/
    script:
        - echo "deploy application to the staging cluster"
        ## Configure kubeconfig
        - mkdir -p ~/.kube/
        - touch config
        # ENCODE - echo $(cat $KUBECONF | base64) | tr -d " "
        - echo $KUBECONF | base64 -d > ~/.kube/config
        - kubectl config set-context --current --namespace=$DEV_NAMESPACE
        - kubectl config view --minify | grep "namespace:"
        ### Update YAML files for Ingress, Service, Deployment
        #- echo $CI_REGISTRY_USER
        #- echo $CI_REGISTRY_PASSWORD
        #- echo $CI_REGISTRY
        #- echo $CI_DEPLOY_USER
        #- echo $CI_DEPLOY_PASSWORD
        - cd deploy
        - kustomize edit set image app-image=$CI_REGISTRY_IMAGE:$USER
        - kustomize edit set namespace $DEV_NAMESPACE
        - mkdir secrets
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > secrets/.dockerconfigjson
        - echo "[{\"op\":\"replace\",\"path\":\"/spec/rules/0/host\",\"value\":\"$DEV_INGRESS_HOST\"}]" > ingress_patch.json
        #- cat ingress_patch.json
        ### Finally, apply all the updated YAML files
        #- kubectl apply -k .
        - kustomize build > deploy.yaml
        - kubectl apply -f deploy.yaml
        - echo "You may now access to the app with the URL - http://$DEV_INGRESS_HOST"

deploy-to-prod-k8s-cluster:
    stage: production
    image: dtzar/helm-kubectl
    before_script:
        - apk --no-cache add git curl bash
        - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        - mv kustomize /usr/local/bin/
        #- echo $CI_SERVER_HOST
        #- echo $GITLAB_USER_LOGIN
        #- echo $CI_PROJECT_NAME
        #- echo $GITLAB_USER_EMAIL
        #- echo $GITLAB_USER_NAME
        #- git remote set-url origin https://$CI_DEPLOY_USER:$CI_DEPLOY_PASSWORD@$CI_SERVER_HOST/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git
        - git remote set-url origin https://$USER:$PASSWORD@$CI_SERVER_HOST/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git
        - git config --global user.email "$GITLAB_USER_EMAIL"
        - git config --global user.name "$GITLAB_USER_NAME"
    script:
        - echo "deploy application to the production cluster"
        - TIMESTAMP=$(date +%s)
        - echo $TIMESTAMP
        - git checkout -B master
        - git pull origin master
        - cd deploy
        - kustomize edit add annotation time:$TIMESTAMP -f
        - kustomize edit set image app-image=$HARBOR_IMAGE:$USER
        - kustomize edit set namespace $PROD_NAMESPACE
        - mkdir secrets
        - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$HARBOR_REGISTRY_USER\",\"password\":\"$HARBOR_REGISTRY_PASSWORD\"}}}" > secrets/.dockerconfigjson
        - echo "[{\"op\":\"replace\",\"path\":\"/spec/rules/0/host\",\"value\":\"$PROD_INGRESS_HOST\"}]" > ingress_patch.json
        #- cat ingress_patch.json
        ### Finally, apply all the updated YAML files
        #- kubectl apply -k .
        - kustomize build > prod/deploy.yaml
        - cat prod/deploy.yaml
        #- kubectl apply -f deploy.yaml
        #- echo "You may now access to the app with the URL - http://$PROD_INGRESS_HOST"
        - git add prod/deploy.yaml
        - git commit -am '[skip ci] PROD deploy.yaml file update'
        - git push origin master
    when: manual
