apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: app
namespace: user-namespace
resources:
#- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: app-image
  newName: new-registry/new-tag
  newTag: new-tag
secretGenerator:
  - name: regcred
    type: kubernetes.io/dockerconfigjson
    files:
      - secrets/.dockerconfigjson
patches:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: app